feat(popover):add popover margin prop
uber/baseweb pull request #3723
Opened 2020-09-02 20:40 UTC by jiaoy14

`Fixes #1, Fixes #2` 

#### Description

#### Scope

2020-09-02 20:53 UTC, chasestarr reviewed
Can you please add a VRT validating the feature?

2020-09-02 22:23 UTC, sandgraham reviewed
We should add this prop to the sandbox on the doc site. You can do that in:
`baseui/documentation-site/components/yard/config/popover.ts`

2020-09-03 18:35 UTC, chasestarr approved these changes
Awesome! this lgtm

2020-09-03 18:37 UTC, chasestarr requested changes

2020-09-03 18:37 UTC, chasestarr commented on src/popover/types.js
> +  popoverMargin: number,
Sorry I missed this, we need to make the prop optional because it will fail flow check for existing applications

2020-09-03 20:28 UTC, chasestarr approved these changes
thanks for the type fix

2020-09-03 21:30 UTC, merged