chore(theme): update colors
uber/baseweb pull request #4520
Opened 2021-09-14 21:25 UTC by lhbrennan

* update yellow600 and gray500
* add backgroundMembership and contentMembership tokens

2021-09-14 23:48 UTC, williamernest approved these changes

2021-09-14 23:48 UTC, williamernest requested changes
After VRT's are landed this LGTM

2021-09-15 03:05 UTC, chasestarr approved these changes

2021-09-15 19:06 UTC, williamernest approved these changes

2021-09-16 19:20 UTC, closed without merging

2021-09-16 19:21 UTC, lhbrennan commented
Requirements have changed significantly on the design side. Abandoning this and starting fresh.